# http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false
addons:
  sauce_connect: true

language: node_js
script: make test
node_js:
- '0.10'
matrix:
  include:
  - env: BROWSER_NAME=chrome BROWSER_VERSION=41
  - env: BROWSER_NAME=chrome BROWSER_VERSION=40
  - env: BROWSER_NAME=firefox BROWSER_VERSION=36
  - env: BROWSER_NAME=firefox BROWSER_VERSION=35
  - env: BROWSER_NAME=ie BROWSER_VERSION=6
  - env: BROWSER_NAME=ie BROWSER_VERSION=7
  - env: BROWSER_NAME=ie BROWSER_VERSION=8
  - env: BROWSER_NAME=ie BROWSER_VERSION=9
  - env: BROWSER_NAME=ie BROWSER_VERSION=10
  - env: BROWSER_NAME=ie BROWSER_VERSION=11
  - env: BROWSER_NAME=safari BROWSER_VERSION=8
  - env: BROWSER_NAME=safari BROWSER_VERSION=7
env:
  global:
  - secure: jpTeSVHr1VjtSL/KGlIdo+0t7+BwKCRVXNkHeZx3dzIiHWmNxf8G1Uo7cVHodJhFAYQpo7cGnVzAV/qyYaIzdSvyuFBkXqJ/symCVMvCLazfCylSyD4+tR3aReedKwYXiS9qXkzCstD7hzAQ8Ts9clz+KVL++qBEFzeY19t7Mcs=
  - secure: hvOI84LiE/zjPpVs4O9TT2BSwoX7mXtImRajqI0Vd4MSomyoLnZiUQ2KynUZOAKoVGyEcbQ2CMnGu1vCSVBCnizI7Ir3nMnAongnz1QA6SHvcyENNV6f9VuXsx0OILF4I7J72/Vr3E5xUc9KO4BYAL7PAmNJY4LK6kSY7y0S/eI=
